main: me.hunterboerner.war.War
name: War
version: 0.1
description: A plugin to have wars within MINECRAFT
author: Theron Boerner
commands:
  War:
    description: This is a blank command
    usage: /war declare [command] type /war help for more info.